Repository Quantco/pixi-pack, pull requests merged in 2024-07, with the labels that each got.

#29 chore: use cross for linux-arm builds
  .github/workflows/build.yml
  .github/workflows/ci.yml
  Cross.toml
Labels: chore

#28 docs: Add conda-forge badge, mention pixi exec
  README.md
Labels: documentation

#33 feat: include package name in error message
  Cargo.lock
  Cargo.toml
  src/unpack.rs
Labels: enhancement

#34 ci: fix release CI
  .cargo/config.toml
  .github/workflows/build.yml
  Cargo.lock
  Cargo.toml
Labels: ci
