Repository Quantco/pixi-pack, pull requests merged in 2024-08, with the labels that each got.

#42 fix: Fix resource leak for tmp dir during unpack
  src/unpack.rs
Labels: fix

#44 chore: Bump to 0.1.6 release
  Cargo.lock
  Cargo.toml
Labels: chore

#36 ci: Build for Windows-ARM as well
  .github/workflows/build.yml
Labels: ci

#45 chore: Bump dependencies
  Cargo.lock
  Cargo.toml
Labels: chore

#47 fix: Fix leaking package cache directory
  Cargo.lock
  Cargo.toml
  src/unpack.rs
Labels: fix
