Repository Quantco/pixi-pack, pull requests merged in 2024-10, with the labels that each got.

#55 fix: Throw error when package download fails
  examples/auth/pixi.lock
  examples/auth/pixi.toml
  src/pack.rs
  tests/integration_test.rs
Labels: fix

#56 ci: Remove merge queue from workflows
  .github/workflows/build.yml
  .github/workflows/ci.yml
Labels: ci

#43 fix: Set timestamps correctly inside pack
  Cargo.lock
  Cargo.toml
  src/pack.rs
  src/util.rs
  tests/integration_test.rs
Labels: fix

#58 chore: Rename local channel to pixi-pack
  README.md
  src/unpack.rs
Labels: chore

#59 feat: Add `--env-name` flag for environment output directory
  Cargo.lock
  Cargo.toml
  src/main.rs
  src/unpack.rs
  tests/integration_test.rs
Labels: enhancement

#62 feat: Write pixi-pack-version to metadata file
  src/lib.rs
  src/main.rs
  src/unpack.rs
Labels: enhancement

#61 fix: Use default when no timestamp is provided in package
  Cargo.lock
  Cargo.toml
  examples/no-timestamp/pixi.lock
  examples/no-timestamp/pixi.toml
  src/pack.rs
  tests/integration_test.rs
Labels: fix
