Repository Quantco/pixi-pack, pull requests merged in 2025-06, with the labels that each got.

#176 feat: Specify pixi-pack version in user agent
  src/pack.rs
Labels: enhancement

#183 chore: Update insta snapshots after release
  tests/snapshots/integration_test__sha256-linux-64-executable.snap
  tests/snapshots/integration_test__sha256-linux-64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-linux-64-pypi.snap
  tests/snapshots/integration_test__sha256-linux-64.snap
  tests/snapshots/integration_test__sha256-linux-aarch64-executable.snap
  tests/snapshots/integration_test__sha256-linux-aarch64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-linux-aarch64-pypi.snap
  tests/snapshots/integration_test__sha256-linux-aarch64.snap
  tests/snapshots/integration_test__sha256-linux-ppc64le-pypi.snap
  tests/snapshots/integration_test__sha256-linux-ppc64le.snap
  tests/snapshots/integration_test__sha256-osx-64-executable.snap
  tests/snapshots/integration_test__sha256-osx-64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-osx-64-pypi.snap
  tests/snapshots/integration_test__sha256-osx-64.snap
  tests/snapshots/integration_test__sha256-osx-arm64-executable.snap
  tests/snapshots/integration_test__sha256-osx-arm64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-osx-arm64-pypi.snap
  tests/snapshots/integration_test__sha256-osx-arm64.snap
  tests/snapshots/integration_test__sha256-win-64-executable.snap
  tests/snapshots/integration_test__sha256-win-64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-win-64-pypi.snap
  tests/snapshots/integration_test__sha256-win-64.snap
Labels: chore

#187 fix: Standalone executable doesn't work
  src/bin/pixi-unpack.rs
  src/header.ps1
  src/header.sh
  tests/snapshots/integration_test__sha256-linux-64-executable.snap
  tests/snapshots/integration_test__sha256-linux-64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-linux-aarch64-executable.snap
  tests/snapshots/integration_test__sha256-linux-aarch64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-osx-64-executable.snap
  tests/snapshots/integration_test__sha256-osx-64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-osx-arm64-executable.snap
  tests/snapshots/integration_test__sha256-osx-arm64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-win-64-executable.snap
  tests/snapshots/integration_test__sha256-win-64-pypi-executable.snap
Labels: fix

#185 fix: Set proper name to binaries
  Cargo.lock
  Cargo.toml
  src/bin/pixi-pack.rs
  src/bin/pixi-unpack.rs
Labels: fix
