Repository Quantco/pixi-pack, pull requests merged in 2025-02, with the labels that each got.

#95 chore: Fix pixi warning
  pixi.toml
Labels: chore

#96 fix: Properly convert filepath to URL during unpacking
  Cargo.lock
  Cargo.toml
  src/unpack.rs
Labels: fix

#97 chore: Adjust shas after release
  tests/snapshots/integration_test__sha256-linux-64-executable.snap
  tests/snapshots/integration_test__sha256-linux-64.snap
  tests/snapshots/integration_test__sha256-linux-aarch64-executable.snap
  tests/snapshots/integration_test__sha256-linux-aarch64.snap
  tests/snapshots/integration_test__sha256-linux-ppc64le.snap
  tests/snapshots/integration_test__sha256-osx-64-executable.snap
  tests/snapshots/integration_test__sha256-osx-64.snap
  tests/snapshots/integration_test__sha256-osx-arm64-executable.snap
  tests/snapshots/integration_test__sha256-osx-arm64.snap
  tests/snapshots/integration_test__sha256-win-64-executable.snap
  tests/snapshots/integration_test__sha256-win-64.snap
Labels: chore

#99 fix: Change default manifest path to cwd
  src/main.rs
Labels: fix

#105 chore: Adjust shas after release
  tests/snapshots/integration_test__sha256-linux-64-executable.snap
  tests/snapshots/integration_test__sha256-linux-64.snap
  tests/snapshots/integration_test__sha256-linux-aarch64-executable.snap
  tests/snapshots/integration_test__sha256-linux-aarch64.snap
  tests/snapshots/integration_test__sha256-linux-ppc64le.snap
  tests/snapshots/integration_test__sha256-osx-64-executable.snap
  tests/snapshots/integration_test__sha256-osx-64.snap
  tests/snapshots/integration_test__sha256-osx-arm64-executable.snap
  tests/snapshots/integration_test__sha256-osx-arm64.snap
  tests/snapshots/integration_test__sha256-win-64-executable.snap
  tests/snapshots/integration_test__sha256-win-64.snap
Labels: chore

#103 docs: Mention add_pip_as_python_dependency in compatibility mode
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: documentation

#106 feat: Use tracing feature from clap-verbosity-flag
  Cargo.lock
  Cargo.toml
  src/main.rs
Labels: enhancement
