Repository Quantco/pixi-pack, pull requests merged in 2025-04, with the labels that each got.

#122 refactor: Use error_for_status in response
  src/pack.rs
  tests/integration_test.rs
Labels: refactor

#116 feat: Add PyPI support
  Cargo.lock
  Cargo.toml
  README.md
  examples/pypi-wheel-packages/pixi.lock
  examples/pypi-wheel-packages/pixi.toml
  pixi.lock
  pixi.toml
  src/build_context.rs
  src/lib.rs
  src/pack.rs
  src/unpack.rs
  tests/integration_test.rs
  tests/snapshots/integration_test__sha256-linux-64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-linux-64-pypi.snap
  tests/snapshots/integration_test__sha256-linux-aarch64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-linux-aarch64-pypi.snap
  tests/snapshots/integration_test__sha256-linux-ppc64le-pypi.snap
  tests/snapshots/integration_test__sha256-osx-64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-osx-64-pypi.snap
  tests/snapshots/integration_test__sha256-osx-arm64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-osx-arm64-pypi.snap
  tests/snapshots/integration_test__sha256-win-64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-win-64-pypi.snap
Labels: enhancement

#125 chore: Adjust shas after release
  tests/snapshots/integration_test__sha256-linux-64-executable.snap
  tests/snapshots/integration_test__sha256-linux-64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-linux-64-pypi.snap
  tests/snapshots/integration_test__sha256-linux-64.snap
  tests/snapshots/integration_test__sha256-linux-aarch64-executable.snap
  tests/snapshots/integration_test__sha256-linux-aarch64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-linux-aarch64-pypi.snap
  tests/snapshots/integration_test__sha256-linux-aarch64.snap
  tests/snapshots/integration_test__sha256-linux-ppc64le-pypi.snap
  tests/snapshots/integration_test__sha256-linux-ppc64le.snap
  tests/snapshots/integration_test__sha256-osx-64-executable.snap
  tests/snapshots/integration_test__sha256-osx-64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-osx-64-pypi.snap
  tests/snapshots/integration_test__sha256-osx-64.snap
  tests/snapshots/integration_test__sha256-osx-arm64-executable.snap
  tests/snapshots/integration_test__sha256-osx-arm64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-osx-arm64-pypi.snap
  tests/snapshots/integration_test__sha256-osx-arm64.snap
  tests/snapshots/integration_test__sha256-win-64-executable.snap
  tests/snapshots/integration_test__sha256-win-64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-win-64-pypi.snap
  tests/snapshots/integration_test__sha256-win-64.snap
Labels: chore

#129 refactor: Refactor --ignore-pypi-errors to --ignore-pypi-non-wheel
  Cargo.lock
  Cargo.toml
  README.md
  examples/pypi-non-wheel-packages/README.md
  examples/pypi-non-wheel-packages/pixi.lock
  examples/pypi-non-wheel-packages/pixi.toml
  examples/pypi-packages/README.md
  src/main.rs
  src/pack.rs
  tests/integration_test.rs
Labels: refactor

#130 chore: Adjust shas after release
  pixi.toml
  tests/snapshots/integration_test__sha256-linux-64-executable.snap
  tests/snapshots/integration_test__sha256-linux-64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-linux-64-pypi.snap
  tests/snapshots/integration_test__sha256-linux-64.snap
  tests/snapshots/integration_test__sha256-linux-aarch64-executable.snap
  tests/snapshots/integration_test__sha256-linux-aarch64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-linux-aarch64-pypi.snap
  tests/snapshots/integration_test__sha256-linux-aarch64.snap
  tests/snapshots/integration_test__sha256-linux-ppc64le-pypi.snap
  tests/snapshots/integration_test__sha256-linux-ppc64le.snap
  tests/snapshots/integration_test__sha256-osx-64-executable.snap
  tests/snapshots/integration_test__sha256-osx-64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-osx-64-pypi.snap
  tests/snapshots/integration_test__sha256-osx-64.snap
  tests/snapshots/integration_test__sha256-osx-arm64-executable.snap
  tests/snapshots/integration_test__sha256-osx-arm64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-osx-arm64-pypi.snap
  tests/snapshots/integration_test__sha256-osx-arm64.snap
  tests/snapshots/integration_test__sha256-win-64-executable.snap
  tests/snapshots/integration_test__sha256-win-64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-win-64-pypi.snap
  tests/snapshots/integration_test__sha256-win-64.snap
Labels: chore

#134 ci: Add OpenSSF Scorecard Analysis
  .github/workflows/scorecard.yml
Labels: ci

#135 chore: Add workflow-dispatch to supply scorecard workflow
  .github/workflows/scorecard.yml
Labels: chore

#137 chore: Use edition 2024
  Cargo.toml
  src/lib.rs
  src/main.rs
  src/pack.rs
  src/unpack.rs
  tests/integration_test.rs
Labels: chore

#138 build: Bump rattler dependencies
  Cargo.lock
  Cargo.toml
  src/pack.rs
  src/unpack.rs
Labels: build

#136 feat: Add s3 and mirror middleware
  Cargo.lock
  Cargo.toml
  README.md
  examples/mirror-middleware/README.md
  examples/mirror-middleware/config.toml
  examples/mirror-middleware/pixi.lock
  examples/mirror-middleware/pixi.toml
  src/main.rs
  src/pack.rs
  tests/integration_test.rs
Labels: enhancement

#141 fix: Auth middleware not used in mirrored channels
  Cargo.lock
  Cargo.toml
  src/pack.rs
Labels: fix

#142 chore: Adjust snapshots after release
  tests/snapshots/integration_test__sha256-linux-64-executable.snap
  tests/snapshots/integration_test__sha256-linux-64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-linux-64-pypi.snap
  tests/snapshots/integration_test__sha256-linux-64.snap
  tests/snapshots/integration_test__sha256-linux-aarch64-executable.snap
  tests/snapshots/integration_test__sha256-linux-aarch64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-linux-aarch64-pypi.snap
  tests/snapshots/integration_test__sha256-linux-aarch64.snap
  tests/snapshots/integration_test__sha256-linux-ppc64le-pypi.snap
  tests/snapshots/integration_test__sha256-linux-ppc64le.snap
  tests/snapshots/integration_test__sha256-osx-64-executable.snap
  tests/snapshots/integration_test__sha256-osx-64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-osx-64-pypi.snap
  tests/snapshots/integration_test__sha256-osx-64.snap
  tests/snapshots/integration_test__sha256-osx-arm64-executable.snap
  tests/snapshots/integration_test__sha256-osx-arm64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-osx-arm64-pypi.snap
  tests/snapshots/integration_test__sha256-osx-arm64.snap
  tests/snapshots/integration_test__sha256-win-64-executable.snap
  tests/snapshots/integration_test__sha256-win-64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-win-64-pypi.snap
  tests/snapshots/integration_test__sha256-win-64.snap
Labels: chore

#144 ci: Use windows arm runner during build
  .github/workflows/build.yml
Labels: ci
