Repository Quantco/pixi-pack, pull requests merged in 2025-05, with the labels that each got.

#151 ci: Simplify build
  .cargo/config.toml
  .github/workflows/build.yml
  Cargo.lock
  Cargo.toml
Labels: ci

#152 chore: Adjust snapshots after release
  tests/snapshots/integration_test__sha256-linux-64-executable.snap
  tests/snapshots/integration_test__sha256-linux-64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-linux-64-pypi.snap
  tests/snapshots/integration_test__sha256-linux-64.snap
  tests/snapshots/integration_test__sha256-linux-aarch64-executable.snap
  tests/snapshots/integration_test__sha256-linux-aarch64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-linux-aarch64-pypi.snap
  tests/snapshots/integration_test__sha256-linux-aarch64.snap
  tests/snapshots/integration_test__sha256-linux-ppc64le-pypi.snap
  tests/snapshots/integration_test__sha256-linux-ppc64le.snap
  tests/snapshots/integration_test__sha256-osx-64-executable.snap
  tests/snapshots/integration_test__sha256-osx-64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-osx-64-pypi.snap
  tests/snapshots/integration_test__sha256-osx-64.snap
  tests/snapshots/integration_test__sha256-osx-arm64-executable.snap
  tests/snapshots/integration_test__sha256-osx-arm64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-osx-arm64-pypi.snap
  tests/snapshots/integration_test__sha256-osx-arm64.snap
  tests/snapshots/integration_test__sha256-win-64-executable.snap
  tests/snapshots/integration_test__sha256-win-64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-win-64-pypi.snap
  tests/snapshots/integration_test__sha256-win-64.snap
Labels: chore

#157 chore: Comment out Cargo.lock in gitignore
  .gitignore
Labels: chore

#156 feat: Support local pixi-pack executables for self-extracting
  Cargo.lock
  Cargo.toml
  README.md
  src/main.rs
  src/pack.rs
  tests/integration_test.rs
Labels: enhancement

#159 chore: Adjust snapshots after release
  tests/snapshots/integration_test__sha256-linux-64-executable.snap
  tests/snapshots/integration_test__sha256-linux-64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-linux-64-pypi.snap
  tests/snapshots/integration_test__sha256-linux-64.snap
  tests/snapshots/integration_test__sha256-linux-aarch64-executable.snap
  tests/snapshots/integration_test__sha256-linux-aarch64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-linux-aarch64-pypi.snap
  tests/snapshots/integration_test__sha256-linux-aarch64.snap
  tests/snapshots/integration_test__sha256-linux-ppc64le-pypi.snap
  tests/snapshots/integration_test__sha256-linux-ppc64le.snap
  tests/snapshots/integration_test__sha256-osx-64-executable.snap
  tests/snapshots/integration_test__sha256-osx-64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-osx-64-pypi.snap
  tests/snapshots/integration_test__sha256-osx-64.snap
  tests/snapshots/integration_test__sha256-osx-arm64-executable.snap
  tests/snapshots/integration_test__sha256-osx-arm64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-osx-arm64-pypi.snap
  tests/snapshots/integration_test__sha256-osx-arm64.snap
  tests/snapshots/integration_test__sha256-win-64-executable.snap
  tests/snapshots/integration_test__sha256-win-64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-win-64-pypi.snap
  tests/snapshots/integration_test__sha256-win-64.snap
Labels: chore

#160 fix: Panic due to duplicate -p handles
  Cargo.lock
  Cargo.toml
  src/main.rs
Labels: fix

#161 chore: Adjust snapshots after release
  tests/snapshots/integration_test__sha256-linux-64-executable.snap
  tests/snapshots/integration_test__sha256-linux-64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-linux-64-pypi.snap
  tests/snapshots/integration_test__sha256-linux-64.snap
  tests/snapshots/integration_test__sha256-linux-aarch64-executable.snap
  tests/snapshots/integration_test__sha256-linux-aarch64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-linux-aarch64-pypi.snap
  tests/snapshots/integration_test__sha256-linux-aarch64.snap
  tests/snapshots/integration_test__sha256-linux-ppc64le-pypi.snap
  tests/snapshots/integration_test__sha256-linux-ppc64le.snap
  tests/snapshots/integration_test__sha256-osx-64-executable.snap
  tests/snapshots/integration_test__sha256-osx-64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-osx-64-pypi.snap
  tests/snapshots/integration_test__sha256-osx-64.snap
  tests/snapshots/integration_test__sha256-osx-arm64-executable.snap
  tests/snapshots/integration_test__sha256-osx-arm64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-osx-arm64-pypi.snap
  tests/snapshots/integration_test__sha256-osx-arm64.snap
  tests/snapshots/integration_test__sha256-win-64-executable.snap
  tests/snapshots/integration_test__sha256-win-64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-win-64-pypi.snap
  tests/snapshots/integration_test__sha256-win-64.snap
Labels: chore

#163 ci: Upload artifact attestation on release
  .github/workflows/build.yml
  README.md
Labels: ci

#166 feat: Support scheme 'file' to process local conda files
  .gitignore
  .typos.toml
  Cargo.lock
  Cargo.toml
  examples/local-channel/channel/noarch/my-webserver-0.1.0-pyh4616a5c_0.conda
  examples/local-channel/channel/noarch/repodata.json
  examples/local-channel/pixi.lock.template
  examples/local-channel/pixi.toml.template
  src/pack.rs
  tests/integration_test.rs
Labels: enhancement

#167 chore: Adjust snapshots after release
  tests/snapshots/integration_test__sha256-linux-64-executable.snap
  tests/snapshots/integration_test__sha256-linux-64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-linux-64-pypi.snap
  tests/snapshots/integration_test__sha256-linux-64.snap
  tests/snapshots/integration_test__sha256-linux-aarch64-executable.snap
  tests/snapshots/integration_test__sha256-linux-aarch64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-linux-aarch64-pypi.snap
  tests/snapshots/integration_test__sha256-linux-aarch64.snap
  tests/snapshots/integration_test__sha256-linux-ppc64le-pypi.snap
  tests/snapshots/integration_test__sha256-linux-ppc64le.snap
  tests/snapshots/integration_test__sha256-osx-64-executable.snap
  tests/snapshots/integration_test__sha256-osx-64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-osx-64-pypi.snap
  tests/snapshots/integration_test__sha256-osx-64.snap
  tests/snapshots/integration_test__sha256-osx-arm64-executable.snap
  tests/snapshots/integration_test__sha256-osx-arm64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-osx-arm64-pypi.snap
  tests/snapshots/integration_test__sha256-osx-arm64.snap
  tests/snapshots/integration_test__sha256-win-64-executable.snap
  tests/snapshots/integration_test__sha256-win-64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-win-64-pypi.snap
  tests/snapshots/integration_test__sha256-win-64.snap
Labels: chore

#168 docs: Add a security policy
  SECURITY.md
Labels: documentation

#170 chore: Adjust snapshots after release
  tests/snapshots/integration_test__sha256-linux-64-executable.snap
  tests/snapshots/integration_test__sha256-linux-64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-linux-64-pypi.snap
  tests/snapshots/integration_test__sha256-linux-64.snap
  tests/snapshots/integration_test__sha256-linux-aarch64-executable.snap
  tests/snapshots/integration_test__sha256-linux-aarch64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-linux-aarch64-pypi.snap
  tests/snapshots/integration_test__sha256-linux-aarch64.snap
  tests/snapshots/integration_test__sha256-linux-ppc64le-pypi.snap
  tests/snapshots/integration_test__sha256-linux-ppc64le.snap
  tests/snapshots/integration_test__sha256-osx-64-executable.snap
  tests/snapshots/integration_test__sha256-osx-64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-osx-64-pypi.snap
  tests/snapshots/integration_test__sha256-osx-64.snap
  tests/snapshots/integration_test__sha256-osx-arm64-executable.snap
  tests/snapshots/integration_test__sha256-osx-arm64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-osx-arm64-pypi.snap
  tests/snapshots/integration_test__sha256-osx-arm64.snap
  tests/snapshots/integration_test__sha256-win-64-executable.snap
  tests/snapshots/integration_test__sha256-win-64-pypi-executable.snap
  tests/snapshots/integration_test__sha256-win-64-pypi.snap
  tests/snapshots/integration_test__sha256-win-64.snap
Labels: chore
